/*
 * gen_kat.c
 *
 * Emits known-answer test vectors for the Cortex-M4 verification
 * harness.
 *
 * The host harnesses check the FFT against an exact __int128 schoolbook
 * multiply computed alongside it.  That oracle cannot cross-compile:
 * __int128 does not exist on 32-bit ARM, and reimplementing 128-bit
 * arithmetic on the target would put new, unverified code in the very
 * place the trust is supposed to come from.
 *
 * So the oracle stays on the host and its results are frozen into a
 * table.  The target then does no exact arithmetic at all -- it runs the
 * FFT and compares against numbers computed by code that is already
 * verified.  The oracle is unchanged in strength; only where it runs has
 * moved.
 *
 * The PRNG, the coefficient ranges and the oracle are duplicated from
 * test_fftmul.c rather than shared, following the convention already
 * established in this repository: test_fftmul.c is a frozen artefact.
 *
 * Usage: gen_kat <out.c> <out.h>
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

/* ==================================================================== */
/* PRNG -- xorshift64*, identical to test_fftmul.c                      */
/* ==================================================================== */

static uint64_t prng_state = 0x9E3779B97F4A7C15ULL;

static void
prng_seed(uint64_t s)
{
	prng_state = s ? s : 0x9E3779B97F4A7C15ULL;
}

static uint64_t
prng_next(void)
{
	prng_state ^= prng_state >> 12;
	prng_state ^= prng_state << 25;
	prng_state ^= prng_state >> 27;
	return prng_state * 0x2545F4914F6CDD1DULL;
}

static int64_t
rand_coeff(int64_t B)
{
	return (int64_t)(prng_next() % (uint64_t)(2 * B + 1)) - B;
}

/* ==================================================================== */
/* Exact oracle -- schoolbook multiply mod X^n + 1, no floating point   */
/* ==================================================================== */

static void
schoolbook_mul(const int64_t *a, const int64_t *b, __int128 *c, size_t n)
{
	size_t i, j, k;

	for (k = 0; k < n; k++) {
		c[k] = 0;
	}
	for (i = 0; i < n; i++) {
		for (j = 0; j < n; j++) {
			k = i + j;
			if (k < n) {
				c[k] += (__int128)a[i] * (__int128)b[j];
			} else {
				c[k - n] -= (__int128)a[i] * (__int128)b[j];
			}
		}
	}
}

/* ==================================================================== */
/* Emission                                                             */
/* ==================================================================== */

/*
 * Cases to emit.  B is the coefficient bound: 25 is the magnitude
 * Falcon-512 actually produces for f, g, F and G, so those cases sit at
 * the scheme's real operating point.  The wider bound exercises the
 * transform further from it without leaving the range where the exact
 * product is still recoverable by rounding.
 */
static const struct {
	unsigned logn;
	int64_t B;
	uint64_t seed;
} cases[] = {
	{ 5, 25,   0xA1B2C3D4E5F60718ULL },
	{ 5, 2048, 0x0F1E2D3C4B5A6978ULL },
	{ 9, 25,   0x123456789ABCDEF0ULL },
	{ 9, 25,   0x0FEDCBA987654321ULL },
	{ 9, 2048, 0x5555AAAA3333CCCCULL },
};

#define NCASES  ((int)(sizeof cases / sizeof cases[0]))

int
main(int argc, char **argv)
{
	FILE *fc, *fh;
	int t;

	if (argc != 3) {
		fprintf(stderr, "usage: %s <out.c> <out.h>\n", argv[0]);
		return 1;
	}
	if ((fc = fopen(argv[1], "w")) == NULL
		|| (fh = fopen(argv[2], "w")) == NULL)
	{
		perror("fopen");
		return 1;
	}

	fprintf(fh,
		"/* Generated by tools/gen_kat.c -- do not edit. */\n\n"
		"#ifndef KAT_H__\n#define KAT_H__\n\n"
		"#include <stdint.h>\n\n"
		"struct kat_case {\n"
		"\tunsigned       logn;\n"
		"\tint64_t        bound;\n"
		"\tconst int16_t *a;\n"
		"\tconst int16_t *b;\n"
		"\tconst int64_t *expect;\n"
		"};\n\n"
		"extern const struct kat_case kat_cases[];\n"
		"extern const unsigned kat_ncases;\n\n"
		"#endif\n");
	fclose(fh);

	fprintf(fc,
		"/* Generated by tools/gen_kat.c -- do not edit. */\n\n"
		"#include \"kat.h\"\n");

	for (t = 0; t < NCASES; t++) {
		size_t n = (size_t)1 << cases[t].logn;
		int64_t *a = malloc(n * sizeof *a);
		int64_t *b = malloc(n * sizeof *b);
		__int128 *c = malloc(n * sizeof *c);
		size_t u;

		if (a == NULL || b == NULL || c == NULL) {
			fprintf(stderr, "allocation failed\n");
			return 1;
		}

		prng_seed(cases[t].seed);
		for (u = 0; u < n; u++) {
			a[u] = rand_coeff(cases[t].B);
		}
		for (u = 0; u < n; u++) {
			b[u] = rand_coeff(cases[t].B);
		}
		schoolbook_mul(a, b, c, n);

		fprintf(fc, "\n/* case %d: logn=%u, |coeff| <= %lld */\n",
			t, cases[t].logn, (long long)cases[t].B);

		fprintf(fc, "static const int16_t a%d[%zu] = {", t, n);
		for (u = 0; u < n; u++) {
			fprintf(fc, "%s%lld", u == 0 ? "\n\t" : (u % 16) ? "," : ",\n\t",
				(long long)a[u]);
		}
		fprintf(fc, "\n};\n");

		fprintf(fc, "static const int16_t b%d[%zu] = {", t, n);
		for (u = 0; u < n; u++) {
			fprintf(fc, "%s%lld", u == 0 ? "\n\t" : (u % 16) ? "," : ",\n\t",
				(long long)b[u]);
		}
		fprintf(fc, "\n};\n");

		/*
		 * The exact coefficients fit comfortably in int64 for these
		 * bounds (worst case n*B^2 = 512*2048^2, about 2^41), but
		 * check rather than assume -- a silent truncation here would
		 * turn the oracle into a source of false failures.
		 */
		fprintf(fc, "static const int64_t e%d[%zu] = {", t, n);
		for (u = 0; u < n; u++) {
			__int128 v = c[u];

			if (v > (__int128)INT64_MAX
				|| v < (__int128)INT64_MIN)
			{
				fprintf(stderr,
					"case %d coeff %zu exceeds int64\n",
					t, u);
				return 1;
			}
			fprintf(fc, "%s%lld", u == 0 ? "\n\t" : (u % 8) ? "," : ",\n\t",
				(long long)(int64_t)v);
		}
		fprintf(fc, "\n};\n");

		free(a);
		free(b);
		free(c);
	}

	fprintf(fc, "\nconst struct kat_case kat_cases[] = {\n");
	for (t = 0; t < NCASES; t++) {
		fprintf(fc, "\t{ %u, %lld, a%d, b%d, e%d },\n",
			cases[t].logn, (long long)cases[t].B, t, t, t);
	}
	fprintf(fc, "};\n\nconst unsigned kat_ncases = %d;\n", NCASES);
	fclose(fc);

	fprintf(stderr, "wrote %d cases to %s / %s\n",
		NCASES, argv[1], argv[2]);
	return 0;
}
